export enum EnumMetadata {
  ROLES = 'ROLES',
  ALLOW_ANONYMOUS = 'ALLOW_ANONYMOUS',
  ALLOW_SECRET = 'ALLOW_SECRET',
  AUTH_CONDITION = 'AUTH_CONDITION',
  ONLY_POSTMAN = 'ONLY_POSTMAN',
  PERMISSIONS = 'PERMISSIONS',
}
